# Generated by Django 5.0.7 on 2024-09-24 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_course_cart_item_courses_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart_item',
        ),
    ]
