# Generated by Django 5.0.7 on 2024-09-24 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_cart_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart_item',
            old_name='user',
            new_name='Value',
        ),
    ]
